server:
  ssl:
    enabled: false
  port: 8080

spring:
  config:
    import: optional:classpath:env.properties
  datasource:
    username: postgres
    password: ${postgres.password}
    url: jdbc:postgresql://localhost:5432/eve_assist_user
  flyway:
    enabled: true
