scheme: http
origins: ${scheme}://localhost:4200
permit-all: /public/**
keycloak-port: 8442
keycloak-realm: EveAssist
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/${keycloak-realm}

esi:
  baseUrl: https://esi.evetech.net/latest
  datasource: tranquility

server:
  error:
    include-message: always
  ssl:
    enabled: false
  port: 8085

spring:
  config:
    import: optional:classpath:env.properties
  datasource:
    username: postgres
    password: ${postgres.password}
    url: jdbc:postgresql://localhost:5432/sdeyaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
          jwk-set-uri: ${keycloak-issuer}/protocol/openid-connect/certs

logging:
  level:
    root: info
    com.eveassist.api.esi: debug

spring-addons:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles

---
spring:
  config:
    activate:
      on-profile: ssl

scheme: https
keycloak-port: 8443

server:
  port: 8043
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/self_signed.p12
    key-store-password: ${self.signed.password}
    key-alias: ${COMPUTERNAME}

