scheme: http
origins: ${scheme}://localhost:4200
permit-all: /public/**
keycloak-port: 8442
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/master

server:
  error:
    include-message: always
  ssl:
    enabled: false

spring:
  config:
    import: optional:classpath:env.properties
  datasource:
    username: postgres
    password: ${postgres.password}
    url: jdbc:postgresql://localhost:5432/eve_assist_user
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
          jwk-set-uri: ${scheme}://localhost:${keycloak-port}/realms/master/protocol/openid-connect/certs


spring-addons:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles

---
scheme: https
keycloak-port: 8443

server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl
