scheme: http
origins: ${scheme}://localhost:4200
permit-all: /public/**
keycloak-port: 8442
keycloak-realm: EveAssist
keycloak-issuer: ${scheme}://localhost:${keycloak-port}/realms/${keycloak-realm}

server:
  error:
    include-message: always
  ssl:
    enabled: false
  port: 8085

spring:
  config:
    import: optional:classpath:env.properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak-issuer}
          jwk-set-uri: ${scheme}://localhost:${keycloak-port}/realms/${keycloak-realm}/protocol/openid-connect/certs

logging:
  level:
    root: warn
    com.eveassist.api.esi: debug

spring-addons:
  issuers:
    - uri: ${keycloak-issuer}
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles

---
scheme: https
keycloak-port: 8443

server:
  port: 8043
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/self_signed.p12
    key-store-password: ${self.signed.password}
    key-alias: ${COMPUTERNAME}

spring:
  config:
    activate:
      on-profile: ssl
