pilot:
  clientId: ${esi.pilot.client.id}
  clientSecret: ${esi.pilot.client.secret}
  redirectUri: https://localhost:9443/pilot/login
  loginUri: https://login.eveonline.com/v2/oauth/authorize/
  tokenUri: https://login.eveonline.com/v2/oauth/token
  responseType: code
  scope:
    - esi-characters.read_notifications.v1
    - esi-killmails.read_killmails.v1
    - esi-skills.read_skills.v1
    - esi-skills.read_skillqueue.v1
    - esi-planets.read_customs_offices.v1
    - esi-planets.manage_planets.v1

scheme: http
ea-api.port: 8085
api-host: ${scheme}://localhost:${ea-api.port}
ui-host: ${scheme}://localhost:${server.port}
keycloak-port: 8442
keycloak-realm: EveAssist
keycloak-base-url: ${scheme}://localhost:${keycloak-port}
keycloak-issuer: ${keycloak-base-url}/realms/${keycloak-realm}

logging:
  level:
    root: info
    com.eveassist.client: debug
    org.springframework.web: debug
    org.springframework.web.servlet.mvc.annotation.RequestMappingHandlerMapping: trace

server:
  port: 7443
  ssl:
    enabled: false

spring:
  config:
    import: optional:classpath:env.properties
  messages:
    basename: i18n/messages
  datasource:
    username: postgres
    password: ${postgres.password}
    url: jdbc:postgresql://localhost:5432/eve_assist_user
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  thymeleaf:
    template-resolver-order: 0
  lifecycle:
    timeout-per-shutdown-phase: 30s

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-issuer}
        registration:
          keycloak-confidential-user:
            authorization-grant-type: authorization_code
            client-name: a local Keycloak instance
            client-id: ${keycloak.eveassist.id}
            client-secret: ${keycloak.eveassist.password}
            provider: keycloak
            scope: openid,profile,email,offline_access

---
spring:
  config:
    activate:
      on-profile: ssl

scheme: https
keycloak-port: 8443
ea-api.port: 8043

server:
  port: 9443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/self_signed.p12
    key-store-password: ${self.signed.password}
    key-alias: ${COMPUTERNAME}
